- import_playbook: playbooks/devops_user_setup.yaml

- import_playbook: playbooks/update_hosts.yaml

- import_playbook: playbooks/master_setup.yaml
  when: groups['jenkins_master'] is defined and groups['jenkins_master'] | length > 0

- import_playbook: playbooks/worker_setup.yaml
  when: groups['jenkins_workers'] is defined and groups['jenkins_workers'] | length > 0

- import_playbook: playbooks/register_worker.yaml
  when: groups['jenkins_workers'] is defined and groups['jenkins_workers'] | length > 0
